//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mez01.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ychet
    {
        public int NomerPost { get; set; }
        public int KodAuto { get; set; }
        public string FIO { get; set; }
        public string Mesyacz { get; set; }
        public int KolvoAuto { get; set; }
    
        public virtual Sprav Sprav { get; set; }
    }
}
